 Check failure on line 1 in .github/workflows/deploy.yml


GitHub Actions
/ .github/workflows/deploy.yml
Invalid workflow file

(Line: 20, Col: 14): Unexpected value ''

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install, build, and upload
        uses: withastro/action@v3
        with:
          # path: . # Si tu proyecto está en la raíz del repo
          # node-version: 20 # Opcional